### PR TITLE
Added link to AMO

### PR DESCRIPTION
**Pull request by Jackymancs4**
Hello @JosephDuffy 
I really like the idea!

As you promised in the README, here is the link to the Mozilla Addons page of your addons :wink:

### CODE REVIEW

**Comment by JosephDuffy** [comment]
Thank you for this -- it's took a long time to get approved and I totally forgot!

**Comment by Jackymancs4** [comment]
Cool! Would you mind if I open a couple of issues with some suggestions?

**Comment by JosephDuffy** [comment]
Sure :) I am planning on working on the feature roadmap soon but more idea certainly welcome!

**Comment by Jackymancs4** [comment]
Closing as I want to rebase onto the new master

**Pull request closed without merging**
